version: 2

aliases:

  - defaults: &defaults
      docker:
        - image: circleci/node:boron
      working_directory: ~/code

  - &restore-repo-cache
      key: repo-{{ .Environment.CIRCLE_SHA1 }}

  - &restore-yarn-cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
  - &save-yarn-cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
        - ~/.cache/yarn
  - &yarn
    |
      yarn install --non-interactive --cache-folder ~/.cache/yarn --frozen-lockfile

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/code

  package_dependencies:
    <<: *defaults
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

  tests:
    <<: *defaults
    docker:
      - image: circleci/node:6-browsers
    steps:
      - restore-cache: *restore-repo-cache
      - restore-cache: *restore-yarn-cache
      - run:
          name: Run tests
          command: node_modules/.bin/ember try:each


workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout_code
      - package_dependencies:
          requires:
            - checkout_code
      - tests:
          requires:
            - package_dependencies
